### ISSUE TITLE
能交流一下吗，最近在研究arduino

### ISSUE THREAD

**Issue by Sloaix** [umview/Arduino#1]
我是做移动开发的，对软件比较熟悉，对硬件一窍不通。这几天入了个sim800c模块，又看到了你的文章，不过和你的gsm模块有点不同，能帮忙看看怎么连arduino uno r3吗？:)

**Comment by lsxiao** [comment]
![Uploading image.png…]()

**Comment by Sloaix** [comment]
<img width="739" alt="qq20171014-145640 2x" src="https://user-images.githubusercontent.com/2627625/31573506-fbc31104-b082-11e7-85e2-87345a771802.png">

**Comment by Sloaix** [comment]
这是taobao老板的引脚图，看不懂为什么这么多gnd
<img width="739" alt="qq20171014-145640 2x" src="https://img.alicdn.com/imgextra/i2/668349063/TB2eeTWastnpuFjSZFvXXbcTpXa_!!668349063.jpg">

**Comment by Sloaix** [comment]
好吧，解决了，电压不够导致一直返回AT+CFUN=1,1命令的结果。:)
